package com.example.license_project_2;

import android.content.Intent;

public enum GeometrySections {
    Fundamental_Concepts_of_Geometry(R.string.SectionOneTheoryDef_8, R.string.SectionOneTheoryProperties_8, R.string.SectionOneTheoryWorkedExamples_8, R.string.SectionOneQuiz_8, R.drawable.oneoneonezero, R.drawable.oneonetwozero, R.drawable.oneonethreezero, R.drawable.oneonefourzero, R.drawable.oneonefivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Geometric_Figures(R.string.SectionTwoTheoryDef_8, R.string.SectionTwoTheoryProperties_8, R.string.SectionTwoTheoryWorkedExamples_8, R.string.SectionTwoQuiz_8, R.drawable.onetwoonezero, R.drawable.onetwotwozero, R.drawable.onetwothreezero, R.drawable.onetwofourzero, R.drawable.onetwofivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Triangles(R.string.SectionOneTheoryDef_9, R.string.SectionOneTheoryProperties_9, R.string.SectionOneTheoryWorkedExamples_9, R.string.SectionOneQuiz_9, R.drawable.twooneonezero, R.drawable.twoonetwozero, R.drawable.twoonethreezero, R.drawable.twoonefourzero, R.drawable.twoonefivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Basic_Geometric_Constructions(R.string.SectionTwoTheoryDef_9, R.string.SectionTwoTheoryProperties_9, R.string.SectionTwoTheoryWorkedExamples_9, R.string.SectionTwoQuiz_9, R.drawable.twotwoonezero, R.drawable.twotwotwozero, R.drawable.twotwothreezero, R.drawable.twotwofourzero, R.drawable.twotwofivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Parallel_Lines(R.string.SectionThreeTheoryDef_9, R.string.SectionThreeTheoryProperties_9, R.string.SectionThreeTheoryWorkedExamples_9, R.string.SectionThreeQuiz_9, R.drawable.twothreeonezero, R.drawable.twothreetwozero, R.drawable.twothreethreezero, R.drawable.twothreefourzero, R.drawable.twothreefivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Quadrilaterals(R.string.SectionFourTheoryDef_9, R.string.SectionFourTheoryProperties_9, R.string.SectionFourTheoryWorkedExamples_9, R.string.SectionFourQuiz_9, R.drawable.testone, R.drawable.testtwo, R.drawable.testthree, R.drawable.testfour, R.drawable.testfive, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Mutual_Position_of_a_Straight_Line_and_a_Circle___Tangent_Line_to_a_Circle(R.string.SectionOneTheoryDef_10, R.string.SectionOneTheoryProperties_10, R.string.SectionOneTheoryWorkedExamples_10, R.string.SectionOneQuiz_10, R.drawable.threeoneonezero, R.drawable.threeonetwozero, R.drawable.threeonethreezero, R.drawable.threeonefourzero, R.drawable.threeonefivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Angles_in_a_Circles(R.string.SectionTwoTheoryDef_10, R.string.SectionTwoTheoryProperties_10, R.string.SectionTwoTheoryWorkedExamples_10, R.string.SectionTwoQuiz_10, R.drawable.threetwoonezero, R.drawable.threetwotwozero, R.drawable.threetwothreezero, R.drawable.threetwofourzero, R.drawable.threetwofivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Properties_of_Chords_and_Diameters_of_a_Circle(R.string.SectionThreeTheoryDef_10, R.string.SectionThreeTheoryProperties_10, R.string.SectionThreeTheoryWorkedExamples_10, R.string.SectionThreeQuiz_10, R.drawable.threethreeonezero, R.drawable.threethreetwozero, R.drawable.threethreethreezero, R.drawable.threethreefourzero, R.drawable.threethreefivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Inscribed_and_Circumscribed_Polygons(R.string.SectionFourTheoryDef_10, R.string.SectionFourTheoryProperties_10, R.string.SectionFourTheoryWorkedExamples_10, R.string.SectionFourQuiz_10, R.drawable.testone, R.drawable.testtwo, R.drawable.testthree, R.drawable.testfour, R.drawable.testfive, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Four_Remarkable_Points_in_a_Triangle(R.string.SectionFiveTheoryDef_10, R.string.SectionFiveTheoryProperties_10, R.string.SectionFiveTheoryWorkedExamples_10, R.string.SectionFiveQuiz_10, R.drawable.testone, R.drawable.testtwo, R.drawable.testthree, R.drawable.testfour, R.drawable.testfive, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Proportional_Line_Segments(R.string.SectionOneTheoryDef_11, R.string.SectionOneTheoryProperties_11, R.string.SectionOneTheoryWorkedExamples_11, R.string.SectionOneQuiz_11, R.drawable.fouroneonezero, R.drawable.fouronetwozero, R.drawable.fouronethreezero, R.drawable.fouronefourzero, R.drawable.fouronefivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Similar_Triangles(R.string.SectionTwoTheoryDef_11, R.string.SectionTwoTheoryProperties_11, R.string.SectionTwoTheoryWorkedExamples_11, R.string.SectionTwoQuiz_11, R.drawable.fourtwoonezero, R.drawable.fourtwotwozero, R.drawable.fourtwothreezero, R.drawable.fourtwofourzero, R.drawable.fourtwofivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Pythagorean_Theorem(R.string.SectionThreeTheoryDef_11, R.string.SectionThreeTheoryProperties_11, R.string.SectionThreeTheoryWorkedExamples_11, R.string.SectionThreeQuiz_11, R.drawable.fourthreeonezero, R.drawable.fourthreetwozero, R.drawable.fourthreethreezero, R.drawable.fourthreefourzero, R.drawable.fourthreefivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Property_of_an_Angle_Bisector_of_a_Triangle___Proportionality_of_Segments_of_Chords_and_Secants(R.string.SectionFourTheoryDef_11, R.string.SectionFourTheoryProperties_11, R.string.SectionFourTheoryWorkedExamples_11, R.string.SectionFourQuiz_11, R.drawable.testone, R.drawable.testtwo, R.drawable.testthree, R.drawable.testfour, R.drawable.testfive, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Similar_Polygons(R.string.SectionFiveTheoryDef_11, R.string.SectionFiveTheoryProperties_11, R.string.SectionFiveTheoryWorkedExamples_11, R.string.SectionFiveQuiz_11, R.drawable.testone, R.drawable.testtwo, R.drawable.testthree, R.drawable.testfour, R.drawable.testfive, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Examples_of_Transformations_of_Figures(R.string.SectionOneTheoryDef_12, R.string.SectionOneTheoryProperties_12, R.string.SectionOneTheoryWorkedExamples_12, R.string.SectionOneQuiz_12, R.drawable.fiveoneonezero, R.drawable.fiveonetwozero, R.drawable.fiveonethreezero, R.drawable.fiveonefourzero, R.drawable.fiveonefivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Motion___Congruence_of_Figures(R.string.SectionTwoTheoryDef_12, R.string.SectionTwoTheoryProperties_12, R.string.SectionTwoTheoryWorkedExamples_12, R.string.SectionTwoQuiz_12, R.drawable.fivetwoonezero, R.drawable.fivetwotwozero, R.drawable.fivetwothreezero, R.drawable.fivetwofourzero, R.drawable.fivetwofivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Transformation_of_Similitude(R.string.SectionThreeTheoryDef_12, R.string.SectionThreeTheoryProperties_12, R.string.SectionThreeTheoryWorkedExamples_12, R.string.SectionThreeQuiz_12, R.drawable.fivethreeonezero, R.drawable.fivethreetwozero, R.drawable.fivethreethreezero, R.drawable.fivethreefourzero, R.drawable.fivethreefivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Addition_and_Subtraction_of_Vectors(R.string.SectionOneTheoryDef_13, R.string.SectionOneTheoryProperties_13, R.string.SectionOneTheoryWorkedExamples_13, R.string.SectionOneQuiz_13, R.drawable.sixoneonezero, R.drawable.sixonetwozero, R.drawable.sixonethreezero, R.drawable.sixonefourzero, R.drawable.sixonefivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Multiplication_of_a_Vector_by_a_Number(R.string.SectionTwoTheoryDef_13, R.string.SectionTwoTheoryProperties_13, R.string.SectionTwoTheoryWorkedExamples_13, R.string.SectionTwoQuiz_13, R.drawable.sixtwoonezero, R.drawable.sixtwotwozero, R.drawable.sixtwothreezero, R.drawable.sixtwofourzero, R.drawable.sixtwofivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Coordinates_of_a_Vector_in_the_Plane(R.string.SectionThreeTheoryDef_13, R.string.SectionThreeTheoryProperties_13, R.string.SectionThreeTheoryWorkedExamples_13, R.string.SectionThreeQuiz_13, R.drawable.sixthreeonezero, R.drawable.sixthreetwozero, R.drawable.sixthreethreezero, R.drawable.sixthreefourzero, R.drawable.sixthreefivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Rotations_Through_Angles_of_Any_Measure(R.string.SectionFourTheoryDef_13, R.string.SectionFourTheoryProperties_13, R.string.SectionFourTheoryWorkedExamples_13, R.string.SectionFourQuiz_13, R.drawable.testone, R.drawable.testtwo, R.drawable.testthree, R.drawable.testfour, R.drawable.testfive, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Trigonometric_Functions___the_Sine_Cosine_and_Tangent_of_an_Angle(R.string.SectionFiveTheoryDef_13, R.string.SectionFiveTheoryProperties_13, R.string.SectionFiveTheoryWorkedExamples_13, R.string.SectionFiveQuiz_13, R.drawable.testone, R.drawable.testtwo, R.drawable.testthree, R.drawable.testfour, R.drawable.testfive, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Relationships_Between_the_Sides_and_Angles_in_a_Right_Triangle(R.string.SectionSixTheoryDef_13, R.string.SectionSixTheoryProperties_13, R.string.SectionSixTheoryWorkedExamples_13, R.string.SectionSixQuiz_13, R.drawable.testone, R.drawable.testtwo, R.drawable.testthree, R.drawable.testfour, R.drawable.testfive, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Metric_Relationships_in_an_Arbitrary_Triangle___Theorem_of_Sines_and_Theorem_of_Cosines(R.string.SectionSevenTheoryDef_13, R.string.SectionSevenTheoryProperties_13, R.string.SectionSevenTheoryWorkedExamples_13, R.string.SectionSevenQuiz_13, R.drawable.testone, R.drawable.testtwo, R.drawable.testthree, R.drawable.testfour, R.drawable.testfive, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Notion_of_the_Area_of_a_Polygon(R.string.SectionOneTheoryDef_14, R.string.SectionOneTheoryProperties_14, R.string.SectionOneTheoryWorkedExamples_14, R.string.SectionOneQuiz_14, R.drawable.sevenoneonezero, R.drawable.sevenonetwozero, R.drawable.sevenonethreezero, R.drawable.sevenonefourzero, R.drawable.sevenonefivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Areas_of_a_Parallelogram__a_Triangle_and_a_Trapezoid(R.string.SectionTwoTheoryDef_14, R.string.SectionTwoTheoryProperties_14, R.string.SectionTwoTheoryWorkedExamples_14, R.string.SectionTwoQuiz_14, R.drawable.seventwoonezero, R.drawable.seventwotwozero, R.drawable.seventwothreezero, R.drawable.seventwofourzero, R.drawable.seventwofivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Area_of_a_Polygon___Ratio_of_the_Areas_of_Similar_Polygons(R.string.SectionThreeTheoryDef_14, R.string.SectionThreeTheoryProperties_14, R.string.SectionThreeTheoryWorkedExamples_14, R.string.SectionThreeQuiz_14, R.drawable.seventhreeonezero, R.drawable.seventhreetwozero, R.drawable.seventhreethreezero, R.drawable.seventhreefourzero, R.drawable.seventhreefivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Regular_Polygons(R.string.SectionOneTheoryDef_15, R.string.SectionOneTheoryProperties_15, R.string.SectionOneTheoryWorkedExamples_15, R.string.SectionOneQuiz_15, R.drawable.eightoneonezero, R.drawable.eightonetwozero, R.drawable.eightonethreezero, R.drawable.eightonefourzero, R.drawable.eightonefivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Length_of_Circumferencе(R.string.SectionTwoTheoryDef_15, R.string.SectionTwoTheoryProperties_15, R.string.SectionTwoTheoryWorkedExamples_15, R.string.SectionTwoQuiz_15, R.drawable.eighttwoonezero, R.drawable.eighttwotwozero, R.drawable.eighttwothreezero, R.drawable.eighttwofourzero, R.drawable.eighttwofivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Area_of_a_Circle(R.string.SectionThreeTheoryDef_15, R.string.SectionThreeTheoryProperties_15, R.string.SectionThreeTheoryWorkedExamples_15, R.string.SectionThreeQuiz_15, R.drawable.eightthreeonezero, R.drawable.eightthreetwozero, R.drawable.eightthreethreezero, R.drawable.eightthreefourzero, R.drawable.eightthreefivezero, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Axioms_of_Solid_Geometry(R.string.SectionOneTheoryDef_16, R.string.SectionOneTheoryProperties_16, R.string.SectionOneTheoryWorkedExamples_16, R.string.SectionOneQuiz_16, R.drawable.nineoneone, R.drawable.nineonetwo, R.drawable.nineonethree, R.drawable.nineonefour, R.drawable.nineonefive, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Straight_Lines_and_Planes_in_Space(R.string.SectionTwoTheoryDef_16, R.string.SectionTwoTheoryProperties_16, R.string.SectionTwoTheoryWorkedExamples_16, R.string.SectionTwoQuiz_16, R.drawable.ninetwoone, R.drawable.ninetwotwo, R.drawable.ninetwothree, R.drawable.ninetwofour, R.drawable.ninetwofive, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Polyhedrons___Right_Prism__Rectangular_Parallelepiped__Pyramid_and_Regular_Pyramid(R.string.SectionThreeTheoryDef_16, R.string.SectionThreeTheoryProperties_16, R.string.SectionThreeTheoryWorkedExamples_16, R.string.SectionThreeQuiz_16, R.drawable.ninethreeone, R.drawable.ninethreetwo, R.drawable.ninethreethree, R.drawable.ninethreefour, R.drawable.ninethreefive, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5),
    Solids_of_Revolution___Cylinder__Cone_and_Ball(R.string.SectionFourTheoryDef_16, R.string.SectionFourTheoryProperties_16, R.string.SectionFourTheoryWorkedExamples_16, R.string.SectionFourQuiz_16, R.drawable.testone, R.drawable.testtwo, R.drawable.testthree, R.drawable.testfour, R.drawable.testfive, R.string.SectionOneAnswerOne, R.string.SectionOneAnswerTwo, R.string.SectionOneAnswerThree, R.string.SectionOneAnswerFour, R.string.SectionOneAnswerFive, R.string.SecOneQuizAnswer1_1, R.string.SecOneQuizAnswer2_1, R.string.SecOneQuizAnswer3_1, R.string.SecOneQuizAnswer1_2, R.string.SecOneQuizAnswer2_2, R.string.SecOneQuizAnswer3_2, R.string.SecOneQuizAnswer1_3, R.string.SecOneQuizAnswer2_3, R.string.SecOneQuizAnswer3_3, R.string.SecOneQuizAnswer1_4, R.string.SecOneQuizAnswer2_4, R.string.SecOneQuizAnswer3_4, R.string.SecOneQuizAnswer1_5, R.string.SecOneQuizAnswer2_5, R.string.SecOneQuizAnswer3_5);
    public final int theoryDef;
    public final int theoryProperties;
    public final int theoryWorkedExamples;
    public final int quiz;
    public final int requirementOne, requirementTwo, requirementThree, requirementFour, requirementFive;
    public final int answerOne_1, answerTwo_1, answerThree_1, answerOne_2, answerTwo_2, answerThree_2, answerOne_3, answerTwo_3, answerThree_3, answerOne_4, answerTwo_4, answerThree_4, answerOne_5, answerTwo_5, answerThree_5;
    public final int correctAnswerOne, correctAnswerTwo, correctAnswerThree, correctAnswerFour, correctAnswerFive;


    GeometrySections(int def, int properties, int examples, int quiz, int one, int two, int three, int four, int five, int correctOne, int correctTwo, int correctThree, int correctFour, int correctFive, int one_1, int two_1, int three_1, int one_2, int two_2, int three_2, int one_3, int two_3, int three_3, int one_4, int two_4, int three_4, int one_5, int two_5, int three_5){
        this.theoryDef = def;
        this.theoryProperties = properties;
        this.theoryWorkedExamples = examples;
        this.quiz = quiz;
        this.requirementOne = one; this.requirementTwo = two; this.requirementThree = three; this.requirementFour = four; this.requirementFive = five;
        this.correctAnswerOne = correctOne; this.correctAnswerTwo = correctTwo; this.correctAnswerThree = correctThree; this.correctAnswerFour = correctFour;
        this.correctAnswerFive = correctFive;
        this.answerOne_1 = one_1; this.answerTwo_1 = two_1; this.answerThree_1 = three_1;
        this.answerOne_2 = one_2; this.answerTwo_2 = two_2; this.answerThree_2 = three_2;
        this.answerOne_3 = one_3; this.answerTwo_3 = two_3; this.answerThree_3 = three_3;
        this.answerOne_4 = one_4; this.answerTwo_4 = two_4; this.answerThree_4 = three_4;
        this.answerOne_5 = one_5; this.answerTwo_5 = two_5; this.answerThree_5 = three_5;
    }

    private static final String NAME = GeometrySections.class.getName();

    public void attachTo(Intent intent){
        intent.putExtra(NAME, ordinal());
    }

    public static GeometrySections detachFrom(Intent intent){
        if(!intent.hasExtra(NAME)) throw new IllegalStateException("No vacation type");
        return values()[intent.getIntExtra(NAME,-1)];
    }
}

